# Generated by Django 3.1.7 on 2021-03-27 12:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_assignment',
            name='PDF',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty_assignment',
            name='current_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 12, 46, 56, 848340, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 12, 46, 56, 847341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 27, 12, 46, 56, 848340, tzinfo=utc)),
        ),
    ]
