# Generated by Django 3.1.7 on 2021-04-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('faculty_id', models.CharField(max_length=50)),
                ('resource_material', models.CharField(max_length=50)),
            ],
        ),
    ]
