# Generated by Django 3.1.7 on 2021-04-03 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 4, 3, 9, 13, 29, 953817, tzinfo=utc)),
        ),
    ]
