# Generated by Django 3.1.7 on 2021-03-30 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20210327_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.CharField(max_length=10)),
                ('course_id', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('PDF', models.FileField(null=True, upload_to='files/')),
                ('time_of_submission', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.CharField(max_length=10)),
                ('course_id', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=200)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='faculty_assignment',
            name='current_year',
        ),
        migrations.RemoveField(
            model_name='faculty_assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='faculty_assignment',
            name='id',
        ),
        migrations.AlterField(
            model_name='faculty_assignment',
            name='PDF',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty_assignment',
            name='assign_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 7, 8, 57, 830985, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 7, 8, 57, 831985, tzinfo=utc)),
        ),
    ]
