# Generated by Django 3.1.7 on 2021-04-01 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20210331_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_course',
            name='course_enrollment_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student_assignment',
            name='PDF',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 6, 47, 20, 642521, tzinfo=utc)),
        ),
    ]
