# Generated by Django 3.1.7 on 2021-03-31 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20210331_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 11, 21, 39, 659307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 11, 21, 39, 660305, tzinfo=utc)),
        ),
    ]
