# Generated by Django 3.1.7 on 2021-04-01 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20210401_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 15, 28, 13, 105097, tzinfo=utc)),
        ),
    ]
