# Generated by Django 3.1.7 on 2021-03-26 16:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20210326_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_assignment',
            name='current_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 16, 58, 39, 634780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='faculty_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 16, 58, 39, 632750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 3, 26, 16, 58, 39, 633785, tzinfo=utc)),
        ),
    ]
