# Generated by Django 3.1.7 on 2021-04-01 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20210401_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_course',
            name='course_enrollment_year',
            field=models.DateField(default=datetime.datetime(2021, 4, 1, 16, 0, 19, 577374, tzinfo=utc)),
        ),
    ]
