# Generated by Django 3.1.7 on 2021-03-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20210326_2228'),
        ('lms', '0003_auto_20210327_0054'),
    ]

    operations = [
    ]
